= Reference-jp

Reference-jp is the repo for the Language Reference documentation of the Arduino syntax in **Japanese**.  
All the Reference terms files are in AsciiDoc format. Manutius, the Arduino platform to manage and publish content, turns Asciidoc documents into HTML pages, PDFs, and more.

Arduinoコンテンツへの貢献ありがとうございます．これらは，Arduinoコミュニティへの助けになります．

== コンテンツの作成と編集
新しいコンテンツを提供したい場合は，新しいファイルを作成し(テキストエディタまたはコードエディタを使用)，「.adoc」として保存してください．  
ファイル名には，括弧や特殊文字を使わないでください．  
以下のURLにてAsciiDoc構文の概要を確認することができます． https://raw.githubusercontent.com/arduino/reference-en/master/AsciiDoc_sample/AsciiDoc_Dictionary/AsciiDoc_Template-Dictionary.adoc[`reference-en/AsciiDoc_sample/AsciiDoc_Dictionary`] こちらには，タイトルや文章，リンク，画像，表，コード，様々なmbed(動画，スライドショー，オーディオまたはコード)が含まれています． レンダリングされたものは， https://https://www.arduino.cc/reference/en/asciidoc_sample/asciidoc_dictionary/asciidoc_template-dictionary/[こちら] で見ることができます．

言語リファレンスや既存のコンテンツを提供したい場合は，2つのテンプレートを確認することができます．reference-jp/AsciiDoc_sample/Reference_Terms:

*link:http://arduino.cc/en/Reference/AnalogWrite[analogWrite] などの用語にはこちらを使用 https://raw.githubusercontent.com/arduino/reference-jp/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Single_Entity.adoc[`AsciiDoc_Template-Single_Entity.adoc`] (レンダリング後は https://https://www.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-single_entity/[こちら]) 

*link:http://arduino.cc/en/Reference/Serial[Serial] などの機能グループにはこちらを使用 https://raw.githubusercontent.com/arduino/reference-jp/master/AsciiDoc_sample/Reference_Terms/AsciiDoc_Template-Parent_Of_Entities.adoc[`AsciiDoc_Template-Parent_Of_Entities.adoc`] (レンダリング後は https://https://www.arduino.cc/reference/en/asciidoc_sample/reference_terms/asciidoc_template-parent_of_entities/[こちら])

すべてのリファレンスのファイルには，説明やコード例，関係する情報へのリンク(参照)が含まれている必要があります．

*コンテンツを他の言語に翻訳したい場合は，以下のURLで「ハイライトされている部分のみ」翻訳するようにしてください．  https://drive.google.com/file/d/0B_6MhyhSmjXeSERydnhleXlLWVk/view[this PDF file for a single Entity] もしくは https://drive.google.com/file/d/0B_6MhyhSmjXeQzVYWC1tZnViNFE/view[this other PDF for Parent of Entities].*

もし，AsciiDocに画像を追加する必要がある場合は，「attachments」というファイルをAsciiDocファイルと同じディレクトリに作成してください．画像はSVGまたはPNGフォーマットで保存でき，最大サイズは200KBとなっています．

== Githubでコンテンツに貢献する
Gitになれていない場合は，オンラインインターフェースを通じてGithubから直接編集することができます． 使い方の短いチュートリアルをまとめています． https://create.arduino.cc/projecthub/Arduino_Genuino/contribute-to-the-arduino-reference-af7c37[確認する！]

adocファイルの編集やArduinoチームへのファイル変更の提案の方法も確認できます．link:https://help.github.com/articles/editing-files-in-another-user-s-repository/[確認する](Githubチームが執筆)   
変更を提案する場合は，リファレンステンプレートのガイドラインに従ってください．


== プルリクエストを投稿する
私たちは，あなたのArduinoリファレンスに対する貢献を嬉しく思っています．これは，コミュニティへを助ける最善の方法となります．

既存のコードや説明を，追加または修正することで貢献することができます．貢献する前には，常に，既存のIssueを参照するか，新しいIssueを開くようにしてください． 

あなたの貢献は，Creative Commons Attribution-Share Alike 3.0の下でライセンスされます．こちらを参照 https://creativecommons.org/licenses/by-sa/3.0/


=== フォルダ構造
[source]
----
reference-jp
├─ AsciiDoc_sample
│   ├── AsciiDoc_Dictionary
│   │   ├── AsciiDoc_Template-Dictionary.adoc
│   │   └── attachments
│   └── Reference_Terms
│       ├── AsciiDoc_Template-Parent_Of_Entities.adoc
│       ├── AsciiDoc_Template-Single_Entity.adoc
│       └── attachments
├── Language
│   ├── Functions
│   ├── Structure
│   └── Variables
├── LICENCE.md
└── README.adoc

----

Languageフォルダの内のファイルツリーは，リンク内のものと同じ構造となります．link:https://www.arduino.cc/reference/en[Arduino Reference webpage]
