---
title: analogRead()
categories: [ "Functions" ]
subCategories: [ "アナログ入出力" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= analogRead()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
指定したアナログピンの電圧を読み取ります．Arduinoには6チャンネル（Mini:8チャンネル，Mega:16チャンネル）あり，10ビットのA/D変換ができます．これは，0-5Vの入力電圧を0-1023の整数値に変換することが可能です．これにより，5V/1024または単位当たり0.0049V(4.9 mV)の分解能を得られることができます．入力レンジと分解能は以下のリンクで変更することが可能です．link:../analogReference[analogReference()]`.

アナログ入力の読み取りには，100マイクロ秒(0.0001s)要するので，最大の読み取りレートは，1秒間に10,000回です．
[%hardbreaks]


[float]
=== 構文

`analogRead(pin)`

[float]
=== パラメータ
`pin`: アナログ入力の読み取りを行うピンの番号(多くのボード:0-5, MiniとNano:0-7, Mega:0-15)

[float]
=== 戻り値
int(0-1023)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
このコードでは，アナログピンの電圧の読み取りとディスプレイ表示を行います．

[source,arduino]
----
int analogPin = 3;     //ポテンショメーターの真ん中の端子をアナログピンの3番に接続
                       //両端の端子は，GNDと+5Vに接続
int val = 0;           //読み取った値を格納する変数

void setup()
{
  Serial.begin(9600);              //シリアルの設定
}

void loop()
{
  val = analogRead(analogPin);     //入力ピンの読み取り
  Serial.println(val);             //値の表示
}
----
[%hardbreaks]

[float]
=== 注意
アナログ入力ピンが未接続の場合，analogRead()から返される値は様々な要素（他のアナログ入力の値または基板と手の距離など）により変動します．

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 参照

[role="language"]
* #LANGUAGE# link:../../arduino-due-only/analogreadresolution[analogReadResolution()]
* #LANGUAGE# http://arduino.cc/en/Tutorial/AnalogInputPins[Tutorial: Analog Input Pins]

--
// SEE ALSO SECTION ENDS