---
title: analogReadResolution()
categories: [ "Functions" ]
subCategories: [ "Arduino DUE のみ" ]
---

:source-highlighter: pygments
:pygments-style: arduino


= analogReadResolution()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
analogReadResolution() は，Arduino Dueのための拡張AnalogAPIです．

analogRead()で返される値のサイズをビット単位で設定します．デフォルトでは，AVRベースのボードとの下位互換性のために10ビットになっています（戻り値は0～1023）．

*Dueは12ビットのA/D変換能力があるので，* 分解能を12ビットに変更して利用することができます．これにより，analogRead()からの戻り値は0～4095になります．
[%hardbreaks]


[float]
=== 構文
`analogReadResolution(bits)`


[float]
=== パラメータ
`bits`:  `analogRead()` 関数からの戻り値の分解能（ビット単位）．これは，1から32の間で設定することができます．12以上に設定することは可能ですが，`analogRead()` からの戻り値は近似値になります．「参照」の項目で詳細を確認してください．

[float]
=== 戻り値
なし

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
このコードでは，A/D変換を異なる分解能で使用する方法を紹介しています．

[source,arduino]
----
void setup() {
  // シリアル接続を開始する
  Serial.begin(9600);
}

void loop() {
  // A0からの入力を標準の分解能で読み取り（10ビット），
  // シリアル通信で送信する
  analogReadResolution(10);
  Serial.print("ADC 10-bit (default) : ");
  Serial.print(analogRead(A0));

  // 分解能を12ビットに変更して読み取る
  analogReadResolution(12);
  Serial.print(", 12-bit : ");
  Serial.print(analogRead(A0));

  // 分解能を16ビットに変更して読み取る
  analogReadResolution(16);
  Serial.print(", 16-bit : ");
  Serial.print(analogRead(A0));

  // 分解能を8ビットに変更して読み取る
  analogReadResolution(8);
  Serial.print(", 8-bit : ");
  Serial.println(analogRead(A0));

  // シリアルモニタを過度に使用しないようにするための少しのディレイ
  delay(100);
}
----
[%hardbreaks]

[float]
=== 注意
`analogReadResolution()` の値を使用しているボードの能力以上に設定した場合は，あまりのビットは0で埋め合わされます．

For example: using the Due with `analogReadResolution(16)` will give you an approximated 16-bit number with the first 12 bits containing the real ADC reading and the last 4 bits *padded with zeros*.

If you set the `analogReadResolution()` value to a value lower than your board's capabilities, the extra least significant bits read from the ADC will be *discarded*.

Using a 16 bit resolution (or any resolution *higher* than actual hardware capabilities) allows you to write sketches that automatically handle devices with a higher resolution ADC when these become available on future boards without changing a line of code.
[%hardbreaks]

[float]
=== See also
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/AnalogInputPins[Description of the analog input pins]

[role="language"]
* #LANGUAGE# link:../../analog-io/analogRead[analogRead()]


--
// HOW TO USE SECTION ENDS
