---
title: Serial.available()
---




= available()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
シリアルポートから読み込み可能なバイト数（文字数）を取得します．これは既に到着し，シリアル受信バッファ（64バイトまで）に保存されているものです．`available()` はStream utility classを継承しています．
[%hardbreaks]


[float]
=== 構文
`Serial.available()`

_Arduino Mega のみ:_

`Serial1.available()` +
`Serial2.available()` +
`Serial3.available()`


[float]
=== パラメータ
なし

[float]
=== 戻り値
読み込み可能なバイト数
--
// OVERVIEW SECTION ENDS





[source,arduino]
----
int incomingByte = 0;	// シリアル受信のために使用

void setup() {
	Serial.begin(9600);	// シリアルポートを開き, 通信速度を9600 bpsに設定
}

void loop() {

	// send data only when you receive data:
	if (Serial.available() > 0) {
		// read the incoming byte:
		incomingByte = Serial.read();

		// say what you got:
		Serial.print("I received: ");
		Serial.println(incomingByte, DEC);
	}
}
----
[%hardbreaks]

*Arduino Megaでの例:*
[source,arduino]
----
void setup() {
  Serial.begin(9600);
  Serial1.begin(9600);

}

void loop() {
  // ポート0から受信し，ポート1に送信
  if (Serial.available()) {
    int inByte = Serial.read();
    Serial1.print(inByte, BYTE);

  }
  // ポート1から受信し，ポート0に送信
  if (Serial1.available()) {
    int inByte = Serial1.read();
    Serial.print(inByte, BYTE);
  }
}
----

[float]
=== 参照
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../available[available()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialEvent[SerialEvent()] +
* #LANGUAGE# link:../../stream/streamAvailable[(Stream.available)]

--
// HOW TO USE SECTION ENDS
