---
title: Serial.begin()
---




= begin()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
シリアル通信のデータレートをビット/秒（bps）で設定します．コンピュータと通信する場合は，以下のいずれかの値を使用してください： 300，600, 1200, 2400, 4800, 9600, 14400, 19200, 28800, 38400, 57600, 115200．ただし，他の値も指定することができます．例として，ピン0と1を使用して，特定のボーレートが必要な機器と通信する場合など．

2番目の引数はオプションであり，パリティとストップビットを設定することができます．デフォルトは，8ビット，パリティなし，1ストップビットです．
[%hardbreaks]


[float]
=== 構文
`Serial.begin(speed)`
`Serial.begin(speed, config)`

_Arduino Megaのみ:_

`Serial1.begin(speed)` +
`Serial2.begin(speed)` +
`Serial3.begin(speed)` +
`Serial1.begin(speed, config)` +
`Serial2.begin(speed, config)` +
`Serial3.begin(speed, config)`



[float]
=== パラメータ
`speed`: データレート (bps) - `long`

`config`: セットデータ, パリティ, ストップビットの設定. 有効な値は：

`SERIAL_5N1` +
`SERIAL_6N1` +
`SERIAL_7N1` +
`SERIAL_8N1` (the default) +
`SERIAL_5N2` +
`SERIAL_6N2` +
`SERIAL_7N2` +
`SERIAL_8N2` +
`SERIAL_5E1` +
`SERIAL_6E1` +
`SERIAL_7E1` +
`SERIAL_8E1` +
`SERIAL_5E2` +
`SERIAL_6E2` +
`SERIAL_7E2` +
`SERIAL_8E2` +
`SERIAL_5O1` +
`SERIAL_6O1` +
`SERIAL_7O1` +
`SERIAL_8O1` +
`SERIAL_5O2` +
`SERIAL_6O2` +
`SERIAL_7O2` +
`SERIAL_8O2` +

[float]
=== 戻り値
なし

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
void setup() {
    Serial.begin(9600); // シリアルポートを開き，通信速度を9600bpsに設定
}

void loop() {}
----
[%hardbreaks]

*Arduino Megaでの例*
[source,arduino]
----
// Arduino Megaの4つ全てのポートを異なる通信速度で使用
// (Serial, Serial1, Serial2, Serial3),

void setup(){
  Serial.begin(9600);
  Serial1.begin(38400);
  Serial2.begin(19200);
  Serial3.begin(4800);

  Serial.println("Hello Computer");
  Serial1.println("Hello Serial 1");
  Serial2.println("Hello Serial 2");
  Serial3.println("Hello Serial 3");
}
void loop() {}
----
[%hardbreaks]
Megaでのコード例をありがとうございます-Jeff Gray

[float]
=== 参照
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../available[available()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialEvent[SerialEvent()]

--
// HOW TO USE SECTION ENDS
