---
title: Serial.print()
---




= print()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
人間の読めるASCII文字の形でデータをシリアルポートに出力します．この関数は様々な形式を使用することができます．数字は，各桁ASCII文字を使用して出力されます．Float型も同様にASCII文字を使用し，デフォルトでは小数点以下2桁まで出力します．Byte型は，1文字の文字として出力されます．文字列とStringはそのまま出力されます．例として，

* `Serial.print(78) の出力は， "78"` +
* `Serial.print(1.23456) の出力は， "1.23"` +
* `Serial.print('N') の出力は， "N"` +
* `Serial.print("Hello world.") の出力は， "Hello world." `

オプションの2番目のパラメータを使うことで，底や小数点を指定することができます．使用可能な値は， `BIN(2進数)`, `OCT(8進数)`, `DEC(10進数)`, `HEX(16進数)` です．Float型の数字では，このパラメータで小数点以下の桁数を指定することができます．例として．

* `Serial.print(78, BIN) の出力は， "1001110"` +
* `Serial.print(78, OCT) の出力は， "116"` +
* `Serial.print(78, DEC) の出力は， "78"` +
* `Serial.print(78, HEX) の出力は， "4E"` +
* `Serial.println(1.23456, 0) の出力は， "1"` +
* `Serial.println(1.23456, 2) の出力は， "1.23"` +
* `Serial.println(1.23456, 4) の出力は， "1.2346"`

フラッシュメモリの文字列もF()で囲むことで，Serial.print()を使用して出力することができます．例として，

`Serial.print(F(“Hello World”))`

1バイト（文字）を送信する場合は， link:../write[Serial.write()]使用してください．
[%hardbreaks]


[float]
=== 構文
`Serial.print(val)` +
`Serial.print(val, format)`


[float]
=== パラメータ
`val`: 出力したい値（全てのデータ型）

[float]
=== 戻り値
`size_t (long)`: `print()` 出力したバイト数．この値を読み取るのは任意です．

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
/*
Forのループを使用し，データを様々なフォーマットで表示するUses a FOR loop for data and prints a number in various formats.
*/
int x = 0;    // 定数

void setup() {
  Serial.begin(9600);      // 9600 bpsでシリアルポートを開く
}

void loop() {
  // ラベルの表示
  Serial.print("NO FORMAT");       // ラベルを表示する
  Serial.print("\t");              // tabを出力

  Serial.print("DEC");
  Serial.print("\t");

  Serial.print("HEX");
  Serial.print("\t");

  Serial.print("OCT");
  Serial.print("\t");

  Serial.print("BIN");
  Serial.print("\t");

  for(x=0; x< 64; x++){    // ASCII表の一部，最適な値に変更する

    // 様々なフォーマットで表示する
    Serial.print(x);       // ASCIIエンコードの10進数として表示，"DEC"と同じ
    Serial.print("\t");    // tabを出力

    Serial.print(x, DEC);  // ASCIIエンコードの10進数として表示
    Serial.print("\t");    // tabを出力

    Serial.print(x, HEX);  // ASCIIエンコードの16進数として表示
    Serial.print("\t");    // tabを出力

    Serial.print(x, OCT);  // ASCIIエンコードの8進数として表示
    Serial.print("\t");    // tabを出力

    Serial.println(x, BIN);  // ASCIIエンコードの2進数として表示
    //                          そして，"println"で改行を出力する．
    delay(200);            // 200ミリ秒待つ
  }
  Serial.println("");      // さらに改行を出力する
}
----
[%hardbreaks]

[float]
=== 注意
バージョン1.0以降の通信は非同期です．`Serial.print()` は文字が送信される前にリターンします．
[%hardbreaks]

[float]
=== 参照
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../available[available()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialEvent[SerialEvent()] +
* #LANGUAGE# link:https://www.arduino.cc/en/Tutorial/Memory[Memory]

--
// HOW TO USE SECTION ENDS
