---
title: Serial.println()
---




= println()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
データを人間が読めるASCII文字の形でシリアルポートに出力し，その後に，復帰コード(ASCII 13, または '\r')と(ASCII 10, または '\n')を出力します．この関数は， link:../print[Serial.print()] と同じ形式です．
[%hardbreaks]


[float]
=== 構文
`Serial.println(val)` +
`Serial.println(val, format)`


[float]
=== パラメータ
`val`: 出力したい値（全てのデータ型）

`format`: int型のデータでは数値の底の指定，float型の場合は小数点以下の桁数の指定

[float]
=== 戻り値
`size_t` (`long`): `println()` 出力したバイト数．この値を読み取るのは任意です．
--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄


[source,arduino]
----
/*
 0番ピンのアナログ入力を読み取り，値を出力します．
 制作： 24 March 2006
 by Tom Igoe
 */

int analogValue = 0;    // アナログ値を格納する定数

void setup() {
  // 9600 bpsでシリアルポートを開く
  Serial.begin(9600);
}

void loop() {
  // 0番ピンのアナログ入力を読み取る
  analogValue = analogRead(0);

  // 様々なフォーマットで表示する
  Serial.println(analogValue);       // ASCIIエンコードの10進数として表
  Serial.println(analogValue, DEC);  // ASCIIエンコードの10進数として表
  Serial.println(analogValue, HEX);  // ASCIIエンコードの16進数として表示
  Serial.println(analogValue, OCT);  // ASCIIエンコードの8進数として表示
  Serial.println(analogValue, BIN);  // ASCIIエンコードの2進数として表示

  // 次の読み込み前に10ミリ秒待つ
  delay(10);
----
[%hardbreaks]

[float]
=== 参照
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../begin[begin()] +
* #LANGUAGE# link:../end[end()] +
* #LANGUAGE# link:../available[available()] +
* #LANGUAGE# link:../read[read()] +
* #LANGUAGE# link:../peek[peek()] +
* #LANGUAGE# link:../flush[flush()] +
* #LANGUAGE# link:../print[print()] +
* #LANGUAGE# link:../println[println()] +
* #LANGUAGE# link:../write[write()] +
* #LANGUAGE# link:../serialEvent[SerialEvent()]
--
// HOW TO USE SECTION ENDS
