---
title: Serial.readBytesUntil()
---




= Serial.readBytesUntil()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
Serial.readBytesUntil() シリアルバッファから読み取った文字列を配列に格納します．終端文字を読み込んだ時や，指定の長さの文字列が読み込まれた時，タイムアウトした時に，この関数は終了されます．（link:../setTimeout[Serial.setTimeout()]を参照）

`Serial.readBytesUntil()` はバッファに読み込まれた文字数を返します．0は有効なデータがなかったことを意味します．

`Serial.readBytesUntil()` はlink:../../stream[Stream] utility classを継承しています．
[%hardbreaks]


[float]
=== 構文
`Serial.readBytesUntil(character, buffer, length)`


[float]
=== パラメータ
`character` : 探したい文字(`char`)

`buffer`: 文字列を格納するバッファ(`char[]` or `byte[]`)

`length` : 読み込むバイト数 (`int`)

[float]
=== 戻り値
`byte`

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 参照
// Link relevant content by category, such as other Reference terms (please add the tag #LANGUAGE#),
// definitions (please add the tag #DEFINITION#), and examples of Projects and Tutorials
// (please add the tag #EXAMPLE#)  ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
[role="language"]
* #LANGUAGE# link:../../stream[Stream] +
* #LANGUAGE# link:../../stream/streamReadBytesUntil[Stream.readByteUntil()]
--
// HOW TO USE SECTION ENDS
