---
title: pulseIn()
categories: [ "Functions" ]
subCategories: [ "応用入出力" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= pulseIn()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
ピンに入力されたのパルス信号を読み取ります(HIGH または LOW). たとえば，`pulseIn()` を *HIGH* に設定した場合, ピンが *HIGH* になった時点を開始時間とし, *LOW* になった時点を終了時間とします．そして，そのパルス幅をマイクロ秒で返します．タイムアウト時間を設定し，タイムアウトした場合は，0を返します．

経験上，この関数で長いパルスを計測するとエラーが発生する場合があります．10マイクロ秒から3分のパルス幅の間で作動します．
[%hardbreaks]


[float]
=== 構文
`pulseIn(pin, value)`

`pulseIn(pin, value, timeout)`

[float]
=== パラメータ
`pin`: パルスを読み取りたいピンの番号 (int)

`value`: 読み取りたいパルスの種類: link:../../../variables/constants/constants/[HIGH] または link:../../../variables/constants/constants/[LOW]. (int)

`timeout` (任意): パルスを何マイクロ秒待つか; 初期値は1秒 (unsigned long)

[float]
=== 戻り値
パルス幅(マイクロ秒)．もし，タイムアウトまでパルスが入力されなかった場合は0 (unsigned long)

--
// OVERVIEW SECTION ENDS




// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== コード例
// Describe what the example code is all about and add relevant code   ►►►►► THIS SECTION IS MANDATORY ◄◄◄◄◄
この例では，7番ピンのパルス幅を測定します．

[source,arduino]
----
int pin = 7;
unsigned long duration;

void setup()
{
  pinMode(pin, INPUT);
}

void loop()
{
  duration = pulseIn(pin, HIGH);
}
----
[%hardbreaks]

--
// HOW TO USE SECTION ENDS
