---
title: tone()
categories: [ "Functions" ]
subCategories: [ "応用入出力" ]
---

:source-highlighter: pygments
:pygments-style: arduino



= tone()


// OVERVIEW SECTION STARTS
[#overview]
--

[float]
=== 説明
指定した周波数の方形波(デューティー比:50%)をピンに生成します．出力時間を指定することができますが，指定しなかった場合は， link:../noTone[noTone()] を実行するまで出力を続けます．ピンは，圧電ブザーまたはスピーカに接続して音を鳴らすことができます．

同時に生成できるのは，1つの周波数のみです．もし，音がすでに他のピンで鳴らされていた場合，tone()を実行しても効果はありません．もし，音を生成しているピンを指定した場合は，周波数は変更されます．

`tone()` を使用すると，3番と11番ピンのPWM出力が出来なくなります(Mega以外).

31Hzより低い音の生成はできません. 技術的詳細は，こちらをご覧ください https://github.com/bhagman/Tone#ugly-details[Brett Hagman's notes].
[%hardbreaks]


[float]
=== 構文
`tone(pin, frequency)`

`tone(pin, frequency, duration)`
[%hardbreaks]

[float]
=== パラメータ
`pin`: 音を生成するピン

`frequency`: 音の周波数(Hz) - `unsigned int`

`duration` (任意): 音の出力時間(マイクロ秒) - `unsigned long`
[%hardbreaks]

[float]
=== 戻り値
なし

--
// OVERVIEW SECTION ENDS


// HOW TO USE SECTION STARTS
[#howtouse]
--

[float]
=== 注意
複数のピンで異なる周波数を生成したい場合は，他のピンで `tone()` を実行する前に `noTone()` を実行する必要があります．
[%hardbreaks]

--
// HOW TO USE SECTION ENDS


// SEE ALSO SECTION
[#see_also]
--

[float]
=== 参照

[role="language"]
* #LANGUAGE# link:../../analog-io/analogwrite[analogWrite()]

[role="example"]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Tone^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone[Pitch follower^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone3[Simple Keyboard^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/Tone4[multiple tones^]
* #EXAMPLE# http://arduino.cc/en/Tutorial/PWM[PWM^]

--
// SEE ALSO SECTION ENDS